site_name: Puzzles and Probability
site_description: Probability, Puzzles, and Decision-Making
site_author: Palashdeep Singh

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Puzzles:
      - Subset of Subsets: puzzles/puzzle01.md
      - First Black Ace: puzzles/puzzle02.md
      - Choosing the Largest Offer: puzzles/puzzle03.md 
      - A Card Game: puzzles/puzzle04.md
      - Monty Hall with a Twist: puzzles/puzzle05.md
      - Penney's Game: puzzles/puzzle06.md
      - Is My Number Higher?: puzzles/puzzle07.md
      - Exponent upon Exponent: puzzles/puzzle08.md
  - About: about.md